import '../../analyzers/models/builder_info.dart';
import '../../analyzers/project_introspector.dart';

/// Renders a "Current Project State" markdown section from a [ProjectSnapshot].
///
/// This section is appended to each AI tool template to give AI assistants
/// real-time awareness of the project's features, builders, and domain models.
String renderProjectSnapshotSection(ProjectSnapshot? snapshot) {
  if (snapshot == null || !snapshot.hasData) {
    return _emptyProjectSection;
  }

  final buffer = StringBuffer();

  buffer.writeln();
  buffer.writeln('---');
  buffer.writeln();
  buffer.writeln('## Current Project State');
  buffer.writeln();
  buffer.writeln(
    'This section was auto-generated by `valenty generate skills` '
    'based on introspection of the current project.',
  );

  // ── Features ──────────────────────────────────────────────────────

  if (snapshot.features.isNotEmpty) {
    buffer.writeln();
    buffer.writeln('### Scaffolded Features');
    buffer.writeln();

    for (final feature in snapshot.features) {
      buffer.writeln('#### Feature: `${feature.name}`');
      buffer.writeln();

      if (feature.scenarioClass.isNotEmpty) {
        buffer.writeln(
          '- **Scenario entry point**: `${feature.scenarioClass}`',
        );
      }

      // Group builders by phase
      final givenBuilders = feature.buildersForPhase('given');
      final whenBuilders = feature.buildersForPhase('when');
      final thenBuilders = feature.buildersForPhase('then');

      if (givenBuilders.isNotEmpty) {
        buffer.writeln();
        buffer.writeln('**Given phase builders:**');
        for (final builder in givenBuilders) {
          buffer.writeln();
          buffer.writeln(
            '- `${builder.className}` (${builder.kindLabel})',
          );
          _renderMethods(buffer, builder);
        }
      }

      if (whenBuilders.isNotEmpty) {
        buffer.writeln();
        buffer.writeln('**When phase builders:**');
        for (final builder in whenBuilders) {
          buffer.writeln();
          buffer.writeln(
            '- `${builder.className}` (${builder.kindLabel})',
          );
          _renderMethods(buffer, builder);
        }
      }

      if (thenBuilders.isNotEmpty) {
        buffer.writeln();
        buffer.writeln('**Then phase builders:**');
        for (final builder in thenBuilders) {
          buffer.writeln();
          buffer.writeln(
            '- `${builder.className}` (${builder.kindLabel})',
          );
          _renderMethods(buffer, builder);
        }
      }

      buffer.writeln();
    }
  } else {
    buffer.writeln();
    buffer.writeln('### Scaffolded Features');
    buffer.writeln();
    buffer.writeln(
      'No features have been scaffolded yet. '
      'Run `valenty scaffold <feature>` to create your first feature builders.',
    );
    buffer.writeln();
  }

  // ── Domain Models ─────────────────────────────────────────────────

  if (snapshot.domainModels.isNotEmpty) {
    buffer.writeln('### Domain Models');
    buffer.writeln();
    buffer.writeln(
      'The following domain model classes were found in `lib/`:',
    );
    buffer.writeln();

    for (final model in snapshot.domainModels) {
      buffer.writeln('- **`${model.className}`** (`${model.filePath}`)');
      for (final prop in model.properties) {
        buffer.writeln('  - `${prop.type} ${prop.name}`');
      }
    }

    buffer.writeln();
  }

  return buffer.toString();
}

void _renderMethods(StringBuffer buffer, BuilderInfo builder) {
  if (builder.methods.isEmpty) return;

  for (final method in builder.methods) {
    final params = method.parameters.isNotEmpty
        ? '(${method.parameters.join(', ')})'
        : _isGetter(method.name)
            ? ''
            : '()';

    if (_isGetter(method.name)) {
      buffer.writeln(
        '  - `.${method.name}` (getter) -> `${method.returnType}`',
      );
    } else {
      buffer.writeln(
        '  - `.${method.name}$params` -> `${method.returnType}`',
      );
    }
  }
}

bool _isGetter(String name) {
  return name == 'when' || name == 'and' || name == 'then';
}

const _emptyProjectSection = '''

---

## Current Project State

No Valenty features or domain models were detected in this project.

To get started:
1. Create your domain models in `lib/`
2. Run `valenty scaffold <feature>` to generate builder files
3. Run `valenty generate skills` again to update this section with your project's structure
''';
